### ISSUE TITLE
Bug 352962 - <type>test-jar</type> no longer resolves to proper dependent classpath 

### ISSUE THREAD

**Issue by mmalmeida** [eclipse-m2e/m2e-core#262]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=352962

Original poster:
Reference:  http://maven.apache.org/guides/mini/guide-attached-tests.html

I have 2 projects, and am trying to make both the source and test artifacts from one to the other in the test scope.  However, the test classes are not being found when using workspace resolution.  I can only get the tests to run when first doing a local install on the dependent projects and disabling workspace resolution.

This was working previously (maybe in 0.13?) when I had <classifier>tests</classifier> included in the dependency.  Following the above referenced Maven documentation, I tried updating this to <type>test-jar</type> - however, neither works properly under m2e 1.0.0 and Eclipse 3.7.

By running the build with "Debug Output", I can see that the \target\classes folder is being put on the classpath twice - once for the source, and another for the test-source.  However, per the m2e-controlled Eclipse configuration on all my projects, the sources have their output folder set to "target/classes", and the test sources have their output set to "target/test-classes".  Removing <type>test-jar</type> removes the duplicate classpath entry shown in the debug output.  As such, it seems pretty clear that m2e is not properly resolving the output folder of the test sources.

Versions:
* m2e - Maven Integration for Eclipse	1.0.0.20110607-2117	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
* Indigo 20110615-0604

**Comment by mmalmeida** [comment]
Opened here because there was no existing "352962 "

**Comment by irbian** [comment]
Looks like related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=365419

**Comment by kwin** [comment]
Probably fixed by https://github.com/eclipse-m2e/m2e-core/commit/9c6d8d55d49bece244dbd5d71f408b7d8f8ef54f.

**Comment by HannesWell** [comment]
Can anyone affected try out the latest m2e snapshot and report if this is fixed?
Thanks.

**Comment by tmortagne** [comment]
> Can anyone affected try out the latest m2e snapshot and report if this is fixed?

I can confirm that trying to use classes coming from a test-jar in the `main/java/` area still is quite a pain in current m2e version (M2E - Maven Integration for Eclipse 2.10.200.20260602-0749), when both modules are in the workspace. So it's not fixed.

https://github.com/eclipse-m2e/m2e-core/pull/2175 seems to be an attempt at fixing this, but there does not seem to be much reaction.

Maybe https://github.com/eclipse-m2e/m2e-core/commit/9c6d8d55d49bece244dbd5d71f408b7d8f8ef54f is only related to the use case in which the module where the test-jar is coming from is not in the workspace.

**Comment by laeubi** [comment]
> I can confirm that trying to use classes coming from a test-jar in the `main/java/` area still is quite a pain

Even though its theoretically possible I would say this is a bit unusual use case anyways.

Beside that I already else where mentioned "classified" artifacts are likely hard if not impossible to map to workspace projects anyways. `test-jar` is a case that *might* work but other just can't as there is not any such "thing" to map it to.

So any complaint like "ist not working for me" is likely not something one can act upon without a concrete example and a detailed description of the expectation of *what* is actually mapped.

**Comment by tmortagne** [comment]
> I would say this is a bit unusual use case anyways.

It's not that exotic IMO, the point of a test-jar is to be reusable like a regular JAR. My specific use case is [a module which entire point is to be a test tool](https://github.com/xwiki/xwiki-platform/tree/master/xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker) (so with its reusable classes in "main/java"), which needs to reuse [tools](https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/internal/junit5/TestExtensionRepository.java#L68) provided by some [test-jar](https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/pom.xml#L122-L139).

**Comment by laeubi** [comment]
> > I would say this is a bit unusual use case anyways.
> 
> It's not that exotic IMO, the point of a test-jar is to be reusable like a regular JAR. My specific use case is [a module which entire point is to be a test tool](https://github.com/xwiki/xwiki-platform/tree/master/xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker) (so with its reusable classes in "main/java"), which needs to reuse [tools](https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/internal/junit5/TestExtensionRepository.java#L68) provided by some [test-jar](https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/pom.xml#L122-L139).

If you have reusable code that is used in main code path why not make it then a regular module in the first place?

**Comment by tmortagne** [comment]
> If you have reusable code that is used in main code path why not make it then a regular module in the first place?

Not really sure what you mean. As mentioned above, there are two different modules involved:
* the dependency module (`A`) contains test tools it's using for its own tests and which could be interesting for others, so it publishes it as a test-jar
* another module (`B`), which is a test library (think junit) exposes features that need to reuse one of the tools provided by `A`'s test-jar

I cannot move the test tool provided by `A` to a dedicated module because it's manipulating main classes provided by `A`. I don't want to move `A`'s tests which need those tools to a different project, since I want `A` to have the tests in charge of validating itself. I don't want to expose that test tool in the main JAR, so I put it in a test-jar (which is pretty much the definition of a test-jar).

I could hack `B` to publish it entirely in as a test-jar, but it's a pretty crappy hack from Maven point of view, and other devs who are not using Eclipse will rightfully not accept this. It will also force having to do the same for any other test module which need to reuse stuff from `B` (and there are several already).

**Comment by tmortagne** [comment]
Here is a simple example to reproduce the problem: [test-jar.zip](https://github.com/user-attachments/files/31166637/test-jar.zip)
